force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APT-{0000}</displayFormat>
        <label>Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Consultation_Fee__c.field-meta.xml
<CustomField>
    <fullName>Consultation_Fee__c</fullName>
    <label>Consultation Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Billable_Visit__c.field-meta.xml
<CustomField>
    <fullName>Billable_Visit__c</fullName>
    <label>Billable Visit</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AppointmentTrigger_Handler.cls
public with sharing class AppointmentTrigger_Handler {
    public static void createInvoiceOnBooking(List<Appointment__c> appList){
        List<Invoice__c> invoiceToCreate = new List<Invoice__c>();
        Set<Id> doctorsId = new Set<Id>();

        //Collect All doctors Ids to Query their fee
        for (Appointment__c appt : appList) {
            if (appt.Doctor__c != null) {
                doctorsId.add(appt.Doctor__c);
            }
        }
        //Query the doctors to get their consultaiton fee
        Map<Id, Doctor__c> docMap = new Map<Id, Doctor__c>();
        if(!doctorsId.isEmpty()){
            docMap = new Map<Id, Doctor__c>([
                SELECT Id, Consultation_Fee__c 
                FROM Doctor__c
                WHERE Id IN :doctorsId
            ]);
        }

        //Build the Invoice
        for(Appointment__c appt : appList){
            Invoice__c inv = new Invoice__c();
            inv.Billable_Visit__c = appt.Id;
            inv.Patient__c = appt.Patient__c;

            Decimal fee = 0;

            if(appt.Doctor__c != null && docMap.containsKey(appt.Doctor__c)){
                Decimal docFee = docMap.get(appt.Doctor__c).Consultation_Fee__c;
                fee = docFee != null ? docFee : 0;
            }

            inv.Total_Amount__c = fee;

            invoiceToCreate.add(inv);

        }
        //save to Database

        if(!invoiceToCreate.isEmpty()){
            insert invoiceToCreate;
        }

    }
}